<?php
function groceries_menu() {
    $items = array();
    $items['groceries_list'] = array(
        'title' => "Groceries!",
        'page callback' => 'show_list',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function show_list() {
    $list['Eggs'] = array(
        'price' => 1.99,
        'quantity' => "2 dozen",
    );

    $list['flower'] = array(
        'price' => 12.99,
        'quantity' => "1",
    );

    $list['hotdog'] = array(
        'price' => 32.99,
        'quantity' => "3 dozen",
    );
    $list['wing'] = array(
        'price' => 22.99,
        'quantity' => "1 dozen",
        
    );

    $display = '<ul>';
    $total = 0;
    foreach ($list as $key => $value) {
        $display .="<li>$key: " .$value['quantity'] . " at " .  $value['price']. "</li>";
        $display .="<li>$key: " .($value['quantity'] * $value['price']). "</li>";
        $total = $total + ($value['price'] * $value['quantity']);
    };

            $display .= "</ul><p>Total: $total </p>";
            return $display;


}

?>
